#!/bin/sh

# Script for system states

case "$(printf "Shutdown\nReboot\nLock\nExit dwm\n" | dmenu -l 10 -i -p "System:")" in
	"Shutdown") poweroff ;;
	"Reboot") reboot ;;
	"Lock") sudo systemctl hibernate ;;
	"Exit dwm") pkill dwm ;;
	*) exit 1 ;;
esac

